# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 14:20


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("letters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="letter_recipients",
                to="encyclopedia.Topic",
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leter_senders",
                to="encyclopedia.Topic",
            ),
        ),
    ]
