# Generated by Django 3.2.2 on 2021-05-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_populate_letter_search_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='footnotes',
            field=models.TextField(blank=True, help_text='Should be HTML.'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='text',
            field=models.TextField(help_text='Should be HTML.'),
        ),
    ]
