# Generated by Django 5.0.7 on 2024-10-21 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0009_alter_topic_order_title'),
        ('letters', '0007_auto_20210527_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_received', to='encyclopedia.topic'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_sent', to='encyclopedia.topic'),
        ),
    ]
