# Generated by Django 5.1.2 on 2024-11-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0008_alter_letter_recipient_alter_letter_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='source',
            field=models.IntegerField(blank=True, choices=[(10, 'Guy de la Bédoyère - Particular Friends'), (15, 'Guy de la Bédoyère - The Letters of Samuel Pepys'), (20, 'Helen Truesdell Heath - The Letters of Samuel Pepys and his Family Circle'), (30, 'Keith Phelps')], null=True),
        ),
    ]
