# Generated by Django 5.1.4 on 2025-02-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0009_alter_letter_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='intro',
            field=models.TextField(blank=True, help_text='Should be HTML.'),
        ),
    ]
