# Because there are a few places where we need to use category IDs, and it's
# least bad if we define them in once place.

PEOPLE = 2

PLACES = 3

# Not an exhaustive list of PLACES categories, but currently the ones that
# are used in the maps dropdown.

PLACES_LONDON_AREAS = 196
PLACES_LONDON_CHURCHES = 31
PLACES_LONDON_GOVERNMENT = 199
PLACES_LONDON_LIVERY_HALLS = 201
PLACES_LONDON_STREETS = 28
PLACES_LONDON_TAVERNS = 27
PLACES_LONDON_THEATRES = 197
PLACES_LONDON_WHITEHALL = 180
PLACES_LONDON_ROYAL = 200
PLACES_LONDON_OTHER = 29

PLACES_LONDON_ENVIRONS = 214
PLACES_BRITAIN_WATERWAYS = 209
PLACES_BRITAIN_REST = 30
PLACES_WORLD_REST = 45
