# Generated by Django 2.1.7 on 2019-03-23 17:39

from django.contrib.postgres.search import SearchVector
from django.db import migrations


def populate_search_index(apps, schema_editor):
    Post = apps.get_model("news", "Post")

    Post.objects.update(
        search_document=(
            SearchVector("title", weight="A")
            + SearchVector("intro", weight="B")
            + SearchVector("text", weight="B")
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_post_search_document"),
    ]

    operations = [
        migrations.RunPython(
            populate_search_index, reverse_code=migrations.RunPython.noop
        ),
    ]
