'use strict';

var gulp = require('gulp');
var del = require('del');
var gutil = require('gulp-util');
var inject = require('gulp-inject');
var rev = require('gulp-rev');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');

var baseDir = 'pepysdiary/common/static'
var sassDir = baseDir + '/src/sass';
var sassFiles = sassDir + '/**/*.scss';
var cssDir = baseDir + '/css';

var templatesDir = './pepysdiary/templates/common';
var templates = [templatesDir + '/base.html'];


/**
 * Delete any existing files generated by this script.
 */
gulp.task('clean', function() {
  return del(cssDir + '/*.css*');
});


/**
 * Create CSS file from Sass files.
 * Create a sourcemap file.
 * Add a revision code to each file.
 */
gulp.task('sass', gulp.series('clean', function buildSass() {
  var sassOptions = {
    outputStyle: 'compressed',
    sourceComments: false
  };

  return gulp.src(sassFiles)
    .pipe(sourcemaps.init())
    .pipe(sass(sassOptions).on('error', sass.logError))
    .pipe(rev())
    .pipe(gulp.dest(cssDir))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(cssDir));
}));


/**
 * Add links to generated CSS files into templates.
 */
gulp.task('inject', function doInjection() {
  var target = gulp.src(templates);

  var sources = gulp.src([
    cssDir + '/**/*.css'
  ], {read: false});

  /**
   * Add Django 'static' formatting.
   */
  var transformFunc = function(filepath) {
    if (filepath.slice(-3) === '.js') {
      return '<script src="{% static \'' + filepath + '\' %}"></script>';
    } else if (filepath.slice(-4) === '.css') {
      return '<link href="{% static \'' + filepath + '\' %}" rel="stylesheet">';
    }
    // Default:
    return inject.transform.apply(inject.transform, arguments);
  };

  var options = {
    ignorePath: '/' + baseDir + '/',
    addRootSlash: false,
    transform: transformFunc
  };

  return target.pipe(inject(sources, options))
    .pipe(gulp.dest(templatesDir))
});


gulp.task('sass:watch', function () {
  gulp.watch(sassFiles, gulp.series(
    'sass',
    'inject'
  ));
});


gulp.task('watch', gulp.parallel('sass:watch'));


gulp.task('default', gulp.series(
  gulp.parallel('sass'),
  'inject'
));

