/**
 * What this does:
 *
 * Compresses Sass files into a CSS file.
 * Creates a CSS sourcemap file.
 * Minifies and combines our JS files into one file.
 * Adds unique revision hashes into the JS and CSS filenames.
 * Injects the new JS and CSS file paths into the base.html tmeplate.
 *
 * Use like:
 *
 *  $ gulp
 *
 * Or, to watch for changes:
 *
 *  $ gulp watch
 */

'use strict';

var gulp        = require('gulp');
var gutil       = require('gulp-util');
var concat      = require('gulp-concat');
var del         = require('del');
var inject      = require('gulp-inject');
var rev         = require('gulp-rev');
var sass        = require('gulp-sass');
var series      = require('stream-series');
var sourcemaps  = require('gulp-sourcemaps');
var uglify      = require('gulp-uglify');


/******************************************************************************
 * VARIABLES
 */

var SRC_DIR       = 'pepysdiary/common/static/common/src';
var STATIC_DIR    = 'pepysdiary/common/static';
var TEMPLATES_DIR = 'pepysdiary/templates/common';

var PATHS = {
  src: {
    sassFiles:      SRC_DIR + '/sass/**/*.scss',
    jsDir:          SRC_DIR + '/js',
    jsVendorDir:    SRC_DIR + '/js/vendor',
    // Our custom file(s):
    jsSiteFiles:    SRC_DIR + '/js/*.js',
  },
  dest: {
    cssDir:         STATIC_DIR + '/common/css',
    cssFiles:       STATIC_DIR + '/common/css/**/*.css',
    jsDir:          STATIC_DIR + '/common/js',
    // All generated JS files:
    jsFiles:        STATIC_DIR + '/common/js/**/*.js'
  },
  templates: {
    files:          [TEMPLATES_DIR + '/base.html']
  }
};


/******************************************************************************
 * Tasks that do the work.
 */


/**
 * Delete any existing files generated by this script.
 */

gulp.task('clean:css', function() {
  // .css and .css.map
  return del(PATHS.dest.cssFiles + '*');
});

gulp.task('clean:js', function() {
  return del(PATHS.dest.jsFiles);
});

gulp.task('clean', gulp.parallel('clean:css', 'clean:js'));


/**
 * Create CSS file from Sass files.
 * Create a sourcemap file.
 * Add a revision code to each file.
 */
gulp.task('sass', gulp.series('clean:css', function buildSass() {
  var sassOptions = {
    outputStyle: 'compressed',
    sourceComments: false
  };

  return gulp.src(PATHS.src.sassFiles)
    .pipe(sourcemaps.init())
      .pipe(sass(sassOptions).on('error', sass.logError))
      .pipe(rev())
      .pipe(gulp.dest(PATHS.dest.cssDir))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(PATHS.dest.cssDir));
}));


/**
 * Minify and combine all the JS files used for all browsers.
 */
gulp.task('js', gulp.series('clean:js', function buildJS() {
  // A stream of our custom JS files, minified.
  var customStream = gulp.src(PATHS.src.jsSiteFiles)
    .pipe(uglify())

  // A stream of the already-minified vendor files.
  var vendorStream = gulp.src([
    PATHS.src.jsVendorDir + '/jquery.min.js',
    PATHS.src.jsVendorDir + '/jquery.timeago.min.js',
    PATHS.src.jsVendorDir + '/bootstrap.min.js'
  ]);

  // Combine both streams of minified JS into one file.
  // Need to be in this order, so jQuery is loaded before our custom JS.
  return series(vendorStream, customStream)
    .pipe(concat('site.min.js'))
    .pipe(rev())
    .pipe(gulp.dest(PATHS.dest.jsDir));
}));


/**
 * Add links to generated CSS files into templates.
 */
gulp.task('inject', function doInjection() {
  var target = gulp.src(PATHS.templates.files);

  var sources = gulp.src([
    PATHS.dest.cssFiles,
    PATHS.dest.jsFiles
  ], {read: false});

  /**
   * Add Django 'static' formatting.
   */
  var transformFunc = function(filepath) {
    if (filepath.slice(-3) === '.js') {
      return '<script src="{% static \'' + filepath + '\' %}"></script>';
    } else if (filepath.slice(-4) === '.css') {
      return '<link href="{% static \'' + filepath + '\' %}" rel="stylesheet">';
    }
    // Default:
    return inject.transform.apply(inject.transform, arguments);
  };

  var options = {
    ignorePath: '/' + STATIC_DIR + '/',
    addRootSlash: false,
    transform: transformFunc
  };

  return target
    .pipe(inject(sources, options))
    .pipe(gulp.dest(TEMPLATES_DIR))
});



/******************************************************************************
 * The Tasks we're most likely to call from the command line.
 */


gulp.task('js:watch', function () {
  // Must have usePolling if running this in a VM, and editing the files on
  // the host, because changes won't be noticed otherwise.
  gulp.watch(PATHS.src.jsSiteFiles, {usePolling: true}, gulp.series(
    'js',
    'inject'
  ));
});


gulp.task('sass:watch', function () {
  // Must have usePolling if running this in a VM, and editing the files on
  // the host, because changes won't be noticed otherwise.
  gulp.watch(PATHS.src.sassFiles, {usePolling: true}, gulp.series(
    'sass',
    'inject'
  ));
});


/**
 * Watch both JS and Sass files for changes.
 */
gulp.task('watch', gulp.parallel('js:watch', 'sass:watch'));


/**
 * Run everything, one time only.
 */
gulp.task('default', gulp.series(
  gulp.parallel('js', 'sass'),
  'inject'
));

