# Generated by Django 4.1.6 on 2023-02-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_dayevent_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="dayevent",
            name="order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optionally used to order events when grouped by Source",
                null=True,
            ),
        ),
    ]
