# Generated by Django 2.1.7 on 2019-04-06 16:17
from django.db import migrations
from django.contrib.postgres.search import SearchVector


def populate_search_index(apps, schema_editor):
    Article = apps.get_model('indepth', 'Article')

    Article.objects.update(
        search_document=(
            SearchVector('title', weight='A') \
            + SearchVector('intro', weight='B') \
            + SearchVector('text', weight='B')
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('indepth', '0003_article_search_document'),
    ]

    operations = [
        migrations.RunPython(populate_search_index, reverse_code=migrations.RunPython.noop),
    ]
