# Generated by Django 3.2.6 on 2021-11-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indepth", "0006_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("book-reviews", "Book reviews"),
                    ("background", "Background"),
                    ("misc", "Miscellaneous"),
                ],
                db_index=True,
                default="misc",
                max_length=25,
            ),
        ),
    ]
