# Generated by Django 3.2.6 on 2021-11-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indepth', '0009_auto_20211105_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_name',
            field=models.CharField(blank=True, help_text='If Author does not have an account, enter their name here instead', max_length=50),
        ),
    ]
