# Generated by Django 3.2.6 on 2021-11-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indepth', '0010_article_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_url',
            field=models.URLField(blank=True, help_text='If Author does not have an account, enter optional URL here instead', max_length=255),
        ),
    ]
