# Generated by Django 2.1.7 on 2019-03-23 15:10

from django.db import migrations
from django.contrib.postgres.search import SearchVector


def populate_search_index(apps, schema_editor):
    Entry = apps.get_model('diary', 'Entry')

    Entry.objects.update(
        search_document=(
            SearchVector('title', weight='A') \
            + SearchVector('text', weight='B') \
            + SearchVector('footnotes', weight='C')
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180115_1635'),
    ]

    operations = [
        migrations.RunPython(populate_search_index, reverse_code=migrations.RunPython.noop),
    ]
