# Generated by Django 2.1.8 on 2019-05-11 15:49

from django.db import connection, migrations


def reset_counter(apps, schema_editor):
    """Having copied all the comments over to annotations, and kept
    their original ids, we need to reset the sequence counter so that
    new annotations are numbered after the most recent one.
    """

    with connection.cursor() as cursor:
        cursor.execute(
            """SELECT setval(pg_get_serial_sequence('"annotations_annotation"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "annotations_annotation";"""  # noqa: E501
        )


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0003_migrate_comments_to_annotations_20190511_1517")
    ]

    operations = [migrations.RunPython(reset_counter)]
