# Generated by Django 3.2.4 on 2021-06-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0006_populate_annotation_search_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="is_removed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=(
                    "Check this box if the comment is inappropriate. "
                    'A "This comment has been removed" message will be displayed '
                    "instead."
                ),
                verbose_name="is removed",
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="object_pk",
            field=models.CharField(
                db_index=True, max_length=64, verbose_name="object ID"
            ),
        ),
    ]
